# docker-compose.yml
version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env.dev
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
     - "${REDIS_PORT}:6379" 
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge